version: "3.9"  # optional since v1.27.0
services:
  server:
    build: .
    ports:
      - "5001:5000"
    depends_on:
        - db
    links:
        - db
    # volumes:
    #   - .:/code
    #   - logvolume01:/var/log
  db:
    image: mysql:8.0.27
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=peachopotato
      - MYSQL_DATABASE=hotornot
      - MYSQL_USER=peach
      - MYSQL_PASSWORD=woody
# volumes:
#   logvolume01: {}
