"""add butterfly table

Revision ID: 69717d66357a
Revises: 
Create Date: 2022-01-15 16:59:48.309419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69717d66357a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('butterflies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('butterflies')
    # ### end Alembic commands ###
