"""add image_url to butterflies

Revision ID: 1070016eedc1
Revises: 6cf22eb91be4
Create Date: 2022-01-15 21:08:59.703721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1070016eedc1'
down_revision = '6cf22eb91be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('butterflies', sa.Column('image_url', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('butterflies', 'image_url')
    # ### end Alembic commands ###
