"""replace voter_ip with session_id on matches

Revision ID: 1dfc05076356
Revises: f9bc039c6ebe
Create Date: 2022-01-29 16:27:50.147652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dfc05076356'
down_revision = 'f9bc039c6ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('session_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_matches_session_id'), 'matches', ['session_id'], unique=False)
    op.drop_column('matches', 'voter_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('voter_ip', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_matches_session_id'), table_name='matches')
    op.drop_column('matches', 'session_id')
    # ### end Alembic commands ###
