"""drop timestamp

Revision ID: 48dd3e98b9b8
Revises: de9be75e2c5b
Create Date: 2022-01-15 22:36:04.031423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48dd3e98b9b8'
down_revision = 'de9be75e2c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('timestamp', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
