"""add worker id to match

Revision ID: 49cf35dc2622
Revises: c0693a1b5f93
Create Date: 2022-02-18 04:21:38.939520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cf35dc2622'
down_revision = 'c0693a1b5f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('worker_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'worker_id')
    # ### end Alembic commands ###
