"""re-add worker id

Revision ID: 67240db5095a
Revises: 5d57ca614e8a
Create Date: 2022-02-13 03:50:22.013679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67240db5095a'
down_revision = '5d57ca614e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_frauds', sa.Column('worker_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_session_frauds_worker_id'), 'session_frauds', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_frauds_worker_id'), table_name='session_frauds')
    op.drop_column('session_frauds', 'worker_id')
    # ### end Alembic commands ###
