"""add name to butterflies

Revision ID: 6cf22eb91be4
Revises: e2075ea49526
Create Date: 2022-01-15 21:02:50.191100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf22eb91be4'
down_revision = 'e2075ea49526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('butterflies', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_butterflies_name'), 'butterflies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_butterflies_name'), table_name='butterflies')
    op.drop_column('butterflies', 'name')
    # ### end Alembic commands ###
