"""add session fraud table

Revision ID: 9e570a1dde2c
Revises: b5bd558acad7
Create Date: 2022-02-12 15:10:42.110577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e570a1dde2c'
down_revision = 'b5bd558acad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_frauds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('frequent_voting_count', sa.Integer(), nullable=False),
    sa.Column('same_side_voting_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_frauds_session_id'), 'session_frauds', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_frauds_worker_id'), 'session_frauds', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_frauds_worker_id'), table_name='session_frauds')
    op.drop_index(op.f('ix_session_frauds_session_id'), table_name='session_frauds')
    op.drop_table('session_frauds')
    # ### end Alembic commands ###
