"""add timestamp to session fraud

Revision ID: a730fc210d6c
Revises: 9e570a1dde2c
Create Date: 2022-02-12 16:08:35.719223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a730fc210d6c'
down_revision = '9e570a1dde2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_frauds', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_frauds', 'timestamp')
    # ### end Alembic commands ###
