"""add comment to match

Revision ID: b5bd558acad7
Revises: f6259be6ac7b
Create Date: 2022-02-10 00:43:05.297750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bd558acad7'
down_revision = 'f6259be6ac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'comment')
    # ### end Alembic commands ###
