"""add other location info

Revision ID: caaa104afc54
Revises: e880b8f45811
Create Date: 2022-01-31 17:13:40.425329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caaa104afc54'
down_revision = 'e880b8f45811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('matches', sa.Column('region', sa.String(length=255), nullable=False))
    op.add_column('matches', sa.Column('country', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'country')
    op.drop_column('matches', 'region')
    op.drop_column('matches', 'city')
    # ### end Alembic commands ###
