"""rename match columns to winner and loser

Revision ID: de9be75e2c5b
Revises: a0a95fd3cadd
Create Date: 2022-01-15 22:29:42.575575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de9be75e2c5b'
down_revision = 'a0a95fd3cadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('loser_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('winner_initial_rating', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('winner_final_rating', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('loser_initial_rating', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('loser_final_rating', sa.Integer(), nullable=False))
    op.drop_column('matches', 'opponent_final_rating')
    op.drop_column('matches', 'opponent_initial_rating')
    op.drop_column('matches', 'player_id')
    op.drop_column('matches', 'opponent_id')
    op.drop_column('matches', 'player_initial_rating')
    op.drop_column('matches', 'player_final_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('player_final_rating', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('player_initial_rating', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('opponent_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('player_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('opponent_initial_rating', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('opponent_final_rating', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('matches', 'loser_final_rating')
    op.drop_column('matches', 'loser_initial_rating')
    op.drop_column('matches', 'winner_final_rating')
    op.drop_column('matches', 'winner_initial_rating')
    op.drop_column('matches', 'loser_id')
    op.drop_column('matches', 'winner_id')
    # ### end Alembic commands ###
