"""add initial tables

Revision ID: e2075ea49526
Revises: 
Create Date: 2022-01-15 20:49:36.741292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2075ea49526'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('butterflies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_butterflies_rating'), 'butterflies', ['rating'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('voter_ip', sa.String(length=255), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('player_initial_rating', sa.Integer(), nullable=False),
    sa.Column('player_final_rating', sa.Integer(), nullable=False),
    sa.Column('opponent_initial_rating', sa.Integer(), nullable=False),
    sa.Column('opponent_final_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_index(op.f('ix_butterflies_rating'), table_name='butterflies')
    op.drop_table('butterflies')
    # ### end Alembic commands ###
