"""add voter ip

Revision ID: e880b8f45811
Revises: 1dfc05076356
Create Date: 2022-01-31 16:56:50.176421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e880b8f45811'
down_revision = '1dfc05076356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('voter_ip', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'voter_ip')
    # ### end Alembic commands ###
