"""add position

Revision ID: f6259be6ac7b
Revises: caaa104afc54
Create Date: 2022-02-09 23:48:47.128138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6259be6ac7b'
down_revision = 'caaa104afc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'position')
    # ### end Alembic commands ###
