"""add timestamp with server timestamp

Revision ID: f9bc039c6ebe
Revises: 48dd3e98b9b8
Create Date: 2022-01-15 22:36:32.133848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bc039c6ebe'
down_revision = '48dd3e98b9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'timestamp')
    # ### end Alembic commands ###
